// flow-typed signature: 83e06545ce2d3c259357d423caff98ee
// flow-typed version: <<STUB>>/bootstrap_v^3.3.7/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap/dist/js/bootstrap' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/npm' {
  declare module.exports: any;
}

declare module 'bootstrap/grunt/bs-commonjs-generator' {
  declare module.exports: any;
}

declare module 'bootstrap/grunt/bs-glyphicons-data-generator' {
  declare module.exports: any;
}

declare module 'bootstrap/grunt/bs-lessdoc-parser' {
  declare module.exports: any;
}

declare module 'bootstrap/grunt/bs-raw-files-generator' {
  declare module.exports: any;
}

declare module 'bootstrap/grunt/change-version' {
  declare module.exports: any;
}

declare module 'bootstrap/Gruntfile' {
  declare module.exports: any;
}

declare module 'bootstrap/js/affix' {
  declare module.exports: any;
}

declare module 'bootstrap/js/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/js/button' {
  declare module.exports: any;
}

declare module 'bootstrap/js/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/js/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/js/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/js/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/js/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/js/transition' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap/dist/js/bootstrap.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap'>;
}
declare module 'bootstrap/dist/js/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap.min'>;
}
declare module 'bootstrap/dist/js/npm.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/npm'>;
}
declare module 'bootstrap/grunt/bs-commonjs-generator.js' {
  declare module.exports: $Exports<'bootstrap/grunt/bs-commonjs-generator'>;
}
declare module 'bootstrap/grunt/bs-glyphicons-data-generator.js' {
  declare module.exports: $Exports<'bootstrap/grunt/bs-glyphicons-data-generator'>;
}
declare module 'bootstrap/grunt/bs-lessdoc-parser.js' {
  declare module.exports: $Exports<'bootstrap/grunt/bs-lessdoc-parser'>;
}
declare module 'bootstrap/grunt/bs-raw-files-generator.js' {
  declare module.exports: $Exports<'bootstrap/grunt/bs-raw-files-generator'>;
}
declare module 'bootstrap/grunt/change-version.js' {
  declare module.exports: $Exports<'bootstrap/grunt/change-version'>;
}
declare module 'bootstrap/Gruntfile.js' {
  declare module.exports: $Exports<'bootstrap/Gruntfile'>;
}
declare module 'bootstrap/js/affix.js' {
  declare module.exports: $Exports<'bootstrap/js/affix'>;
}
declare module 'bootstrap/js/alert.js' {
  declare module.exports: $Exports<'bootstrap/js/alert'>;
}
declare module 'bootstrap/js/button.js' {
  declare module.exports: $Exports<'bootstrap/js/button'>;
}
declare module 'bootstrap/js/carousel.js' {
  declare module.exports: $Exports<'bootstrap/js/carousel'>;
}
declare module 'bootstrap/js/collapse.js' {
  declare module.exports: $Exports<'bootstrap/js/collapse'>;
}
declare module 'bootstrap/js/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/js/dropdown'>;
}
declare module 'bootstrap/js/modal.js' {
  declare module.exports: $Exports<'bootstrap/js/modal'>;
}
declare module 'bootstrap/js/popover.js' {
  declare module.exports: $Exports<'bootstrap/js/popover'>;
}
declare module 'bootstrap/js/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/js/scrollspy'>;
}
declare module 'bootstrap/js/tab.js' {
  declare module.exports: $Exports<'bootstrap/js/tab'>;
}
declare module 'bootstrap/js/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/js/tooltip'>;
}
declare module 'bootstrap/js/transition.js' {
  declare module.exports: $Exports<'bootstrap/js/transition'>;
}
