// flow-typed signature: 61ce56d2fce972f3a4f9e9ffaadd375c
// flow-typed version: <<STUB>>/console.table_v^0.10.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'console.table'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'console.table' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'console.table/dist/console.table' {
  declare module.exports: any;
}

declare module 'console.table/dist/console.table.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'console.table/dist/console.table.js' {
  declare module.exports: $Exports<'console.table/dist/console.table'>;
}
declare module 'console.table/dist/console.table.min.js' {
  declare module.exports: $Exports<'console.table/dist/console.table.min'>;
}
declare module 'console.table/index' {
  declare module.exports: $Exports<'console.table'>;
}
declare module 'console.table/index.js' {
  declare module.exports: $Exports<'console.table'>;
}
