// flow-typed signature: 1b29326ad062b165b5a8e3c16b3f8e95
// flow-typed version: <<STUB>>/cpx_v^1.5.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cpx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cpx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cpx/bin/help' {
  declare module.exports: any;
}

declare module 'cpx/bin/index' {
  declare module.exports: any;
}

declare module 'cpx/bin/main' {
  declare module.exports: any;
}

declare module 'cpx/bin/version' {
  declare module.exports: any;
}

declare module 'cpx/lib/copy-sync' {
  declare module.exports: any;
}

declare module 'cpx/lib/copy' {
  declare module.exports: any;
}

declare module 'cpx/lib/cpx' {
  declare module.exports: any;
}

declare module 'cpx/lib/index' {
  declare module.exports: any;
}

declare module 'cpx/lib/queue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cpx/bin/help.js' {
  declare module.exports: $Exports<'cpx/bin/help'>;
}
declare module 'cpx/bin/index.js' {
  declare module.exports: $Exports<'cpx/bin/index'>;
}
declare module 'cpx/bin/main.js' {
  declare module.exports: $Exports<'cpx/bin/main'>;
}
declare module 'cpx/bin/version.js' {
  declare module.exports: $Exports<'cpx/bin/version'>;
}
declare module 'cpx/lib/copy-sync.js' {
  declare module.exports: $Exports<'cpx/lib/copy-sync'>;
}
declare module 'cpx/lib/copy.js' {
  declare module.exports: $Exports<'cpx/lib/copy'>;
}
declare module 'cpx/lib/cpx.js' {
  declare module.exports: $Exports<'cpx/lib/cpx'>;
}
declare module 'cpx/lib/index.js' {
  declare module.exports: $Exports<'cpx/lib/index'>;
}
declare module 'cpx/lib/queue.js' {
  declare module.exports: $Exports<'cpx/lib/queue'>;
}
