// flow-typed signature: 18e7570ee43c22def490fca10c00dbf1
// flow-typed version: <<STUB>>/electron-packager_v^12.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-packager'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-packager' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-packager/cli' {
  declare module.exports: any;
}

declare module 'electron-packager/common' {
  declare module.exports: any;
}

declare module 'electron-packager/download' {
  declare module.exports: any;
}

declare module 'electron-packager/hooks' {
  declare module.exports: any;
}

declare module 'electron-packager/ignore' {
  declare module.exports: any;
}

declare module 'electron-packager/infer' {
  declare module.exports: any;
}

declare module 'electron-packager/linux' {
  declare module.exports: any;
}

declare module 'electron-packager/mac' {
  declare module.exports: any;
}

declare module 'electron-packager/platform' {
  declare module.exports: any;
}

declare module 'electron-packager/prune' {
  declare module.exports: any;
}

declare module 'electron-packager/targets' {
  declare module.exports: any;
}

declare module 'electron-packager/test/_setup' {
  declare module.exports: any;
}

declare module 'electron-packager/test/_util' {
  declare module.exports: any;
}

declare module 'electron-packager/test/asar' {
  declare module.exports: any;
}

declare module 'electron-packager/test/basic' {
  declare module.exports: any;
}

declare module 'electron-packager/test/ci/_before_script' {
  declare module.exports: any;
}

declare module 'electron-packager/test/cli' {
  declare module.exports: any;
}

declare module 'electron-packager/test/darwin' {
  declare module.exports: any;
}

declare module 'electron-packager/test/fixtures/basic-renamed-to-electron/main' {
  declare module.exports: any;
}

declare module 'electron-packager/test/fixtures/basic/main' {
  declare module.exports: any;
}

declare module 'electron-packager/test/fixtures/el-0374/main' {
  declare module.exports: any;
}

declare module 'electron-packager/test/fixtures/electron-in-dependencies/main' {
  declare module.exports: any;
}

declare module 'electron-packager/test/hooks' {
  declare module.exports: any;
}

declare module 'electron-packager/test/ignore' {
  declare module.exports: any;
}

declare module 'electron-packager/test/index' {
  declare module.exports: any;
}

declare module 'electron-packager/test/infer' {
  declare module.exports: any;
}

declare module 'electron-packager/test/mas' {
  declare module.exports: any;
}

declare module 'electron-packager/test/prune' {
  declare module.exports: any;
}

declare module 'electron-packager/test/targets' {
  declare module.exports: any;
}

declare module 'electron-packager/test/win32' {
  declare module.exports: any;
}

declare module 'electron-packager/win32' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-packager/cli.js' {
  declare module.exports: $Exports<'electron-packager/cli'>;
}
declare module 'electron-packager/common.js' {
  declare module.exports: $Exports<'electron-packager/common'>;
}
declare module 'electron-packager/download.js' {
  declare module.exports: $Exports<'electron-packager/download'>;
}
declare module 'electron-packager/hooks.js' {
  declare module.exports: $Exports<'electron-packager/hooks'>;
}
declare module 'electron-packager/ignore.js' {
  declare module.exports: $Exports<'electron-packager/ignore'>;
}
declare module 'electron-packager/index' {
  declare module.exports: $Exports<'electron-packager'>;
}
declare module 'electron-packager/index.js' {
  declare module.exports: $Exports<'electron-packager'>;
}
declare module 'electron-packager/infer.js' {
  declare module.exports: $Exports<'electron-packager/infer'>;
}
declare module 'electron-packager/linux.js' {
  declare module.exports: $Exports<'electron-packager/linux'>;
}
declare module 'electron-packager/mac.js' {
  declare module.exports: $Exports<'electron-packager/mac'>;
}
declare module 'electron-packager/platform.js' {
  declare module.exports: $Exports<'electron-packager/platform'>;
}
declare module 'electron-packager/prune.js' {
  declare module.exports: $Exports<'electron-packager/prune'>;
}
declare module 'electron-packager/targets.js' {
  declare module.exports: $Exports<'electron-packager/targets'>;
}
declare module 'electron-packager/test/_setup.js' {
  declare module.exports: $Exports<'electron-packager/test/_setup'>;
}
declare module 'electron-packager/test/_util.js' {
  declare module.exports: $Exports<'electron-packager/test/_util'>;
}
declare module 'electron-packager/test/asar.js' {
  declare module.exports: $Exports<'electron-packager/test/asar'>;
}
declare module 'electron-packager/test/basic.js' {
  declare module.exports: $Exports<'electron-packager/test/basic'>;
}
declare module 'electron-packager/test/ci/_before_script.js' {
  declare module.exports: $Exports<'electron-packager/test/ci/_before_script'>;
}
declare module 'electron-packager/test/cli.js' {
  declare module.exports: $Exports<'electron-packager/test/cli'>;
}
declare module 'electron-packager/test/darwin.js' {
  declare module.exports: $Exports<'electron-packager/test/darwin'>;
}
declare module 'electron-packager/test/fixtures/basic-renamed-to-electron/main.js' {
  declare module.exports: $Exports<'electron-packager/test/fixtures/basic-renamed-to-electron/main'>;
}
declare module 'electron-packager/test/fixtures/basic/main.js' {
  declare module.exports: $Exports<'electron-packager/test/fixtures/basic/main'>;
}
declare module 'electron-packager/test/fixtures/el-0374/main.js' {
  declare module.exports: $Exports<'electron-packager/test/fixtures/el-0374/main'>;
}
declare module 'electron-packager/test/fixtures/electron-in-dependencies/main.js' {
  declare module.exports: $Exports<'electron-packager/test/fixtures/electron-in-dependencies/main'>;
}
declare module 'electron-packager/test/hooks.js' {
  declare module.exports: $Exports<'electron-packager/test/hooks'>;
}
declare module 'electron-packager/test/ignore.js' {
  declare module.exports: $Exports<'electron-packager/test/ignore'>;
}
declare module 'electron-packager/test/index.js' {
  declare module.exports: $Exports<'electron-packager/test/index'>;
}
declare module 'electron-packager/test/infer.js' {
  declare module.exports: $Exports<'electron-packager/test/infer'>;
}
declare module 'electron-packager/test/mas.js' {
  declare module.exports: $Exports<'electron-packager/test/mas'>;
}
declare module 'electron-packager/test/prune.js' {
  declare module.exports: $Exports<'electron-packager/test/prune'>;
}
declare module 'electron-packager/test/targets.js' {
  declare module.exports: $Exports<'electron-packager/test/targets'>;
}
declare module 'electron-packager/test/win32.js' {
  declare module.exports: $Exports<'electron-packager/test/win32'>;
}
declare module 'electron-packager/win32.js' {
  declare module.exports: $Exports<'electron-packager/win32'>;
}
