// flow-typed signature: e4e4efffc9a0f31688f6f4d5220e2366
// flow-typed version: <<STUB>>/fast-csv_v^2.4.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-csv'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fast-csv' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fast-csv/lib/extended' {
  declare module.exports: any;
}

declare module 'fast-csv/lib/formatter/formatter_stream' {
  declare module.exports: any;
}

declare module 'fast-csv/lib/formatter/formatter' {
  declare module.exports: any;
}

declare module 'fast-csv/lib/formatter/index' {
  declare module.exports: any;
}

declare module 'fast-csv/lib/index' {
  declare module.exports: any;
}

declare module 'fast-csv/lib/parser/index' {
  declare module.exports: any;
}

declare module 'fast-csv/lib/parser/parser_stream' {
  declare module.exports: any;
}

declare module 'fast-csv/lib/parser/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fast-csv/index' {
  declare module.exports: $Exports<'fast-csv'>;
}
declare module 'fast-csv/index.js' {
  declare module.exports: $Exports<'fast-csv'>;
}
declare module 'fast-csv/lib/extended.js' {
  declare module.exports: $Exports<'fast-csv/lib/extended'>;
}
declare module 'fast-csv/lib/formatter/formatter_stream.js' {
  declare module.exports: $Exports<'fast-csv/lib/formatter/formatter_stream'>;
}
declare module 'fast-csv/lib/formatter/formatter.js' {
  declare module.exports: $Exports<'fast-csv/lib/formatter/formatter'>;
}
declare module 'fast-csv/lib/formatter/index.js' {
  declare module.exports: $Exports<'fast-csv/lib/formatter/index'>;
}
declare module 'fast-csv/lib/index.js' {
  declare module.exports: $Exports<'fast-csv/lib/index'>;
}
declare module 'fast-csv/lib/parser/index.js' {
  declare module.exports: $Exports<'fast-csv/lib/parser/index'>;
}
declare module 'fast-csv/lib/parser/parser_stream.js' {
  declare module.exports: $Exports<'fast-csv/lib/parser/parser_stream'>;
}
declare module 'fast-csv/lib/parser/parser.js' {
  declare module.exports: $Exports<'fast-csv/lib/parser/parser'>;
}
