// flow-typed signature: b50ec7eef7179691c978ae483e42d5f2
// flow-typed version: <<STUB>>/oneref_v^0.3.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oneref'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oneref' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oneref/lib/AppContainer' {
  declare module.exports: any;
}

declare module 'oneref/lib/index' {
  declare module.exports: any;
}

declare module 'oneref/lib/oneRef' {
  declare module.exports: any;
}

declare module 'oneref/src/AppContainer' {
  declare module.exports: any;
}

declare module 'oneref/src/index' {
  declare module.exports: any;
}

declare module 'oneref/src/oneRef' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oneref/lib/AppContainer.js' {
  declare module.exports: $Exports<'oneref/lib/AppContainer'>;
}
declare module 'oneref/lib/index.js' {
  declare module.exports: $Exports<'oneref/lib/index'>;
}
declare module 'oneref/lib/oneRef.js' {
  declare module.exports: $Exports<'oneref/lib/oneRef'>;
}
declare module 'oneref/src/AppContainer.js' {
  declare module.exports: $Exports<'oneref/src/AppContainer'>;
}
declare module 'oneref/src/index.js' {
  declare module.exports: $Exports<'oneref/src/index'>;
}
declare module 'oneref/src/oneRef.js' {
  declare module.exports: $Exports<'oneref/src/oneRef'>;
}
