// flow-typed signature: 0874e6cc72ddea515b9fd2c71cee2239
// flow-typed version: <<STUB>>/react-dnd_v^5.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd/dist/ReactDnD' {
  declare module.exports: any;
}

declare module 'react-dnd/dist/ReactDnD.min' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/createSourceConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/createSourceFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/createSourceMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/createTargetConnector' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/createTargetFactory' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/createTargetMonitor' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/decorateHandler' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/DragDropContext' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/DragLayer' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/DragSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/DropTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/registerSource' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/registerTarget' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/checkDecoratorArguments' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/cloneWithRef' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/disposables/CompositeDisposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/disposables/Disposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/disposables/index' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/disposables/SerialDisposable' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/utils/isValidType' {
  declare module.exports: any;
}

declare module 'react-dnd/lib/wrapConnectorHooks' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd/dist/ReactDnD.js' {
  declare module.exports: $Exports<'react-dnd/dist/ReactDnD'>;
}
declare module 'react-dnd/dist/ReactDnD.min.js' {
  declare module.exports: $Exports<'react-dnd/dist/ReactDnD.min'>;
}
declare module 'react-dnd/lib/createSourceConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/createSourceConnector'>;
}
declare module 'react-dnd/lib/createSourceFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/createSourceFactory'>;
}
declare module 'react-dnd/lib/createSourceMonitor.js' {
  declare module.exports: $Exports<'react-dnd/lib/createSourceMonitor'>;
}
declare module 'react-dnd/lib/createTargetConnector.js' {
  declare module.exports: $Exports<'react-dnd/lib/createTargetConnector'>;
}
declare module 'react-dnd/lib/createTargetFactory.js' {
  declare module.exports: $Exports<'react-dnd/lib/createTargetFactory'>;
}
declare module 'react-dnd/lib/createTargetMonitor.js' {
  declare module.exports: $Exports<'react-dnd/lib/createTargetMonitor'>;
}
declare module 'react-dnd/lib/decorateHandler.js' {
  declare module.exports: $Exports<'react-dnd/lib/decorateHandler'>;
}
declare module 'react-dnd/lib/DragDropContext.js' {
  declare module.exports: $Exports<'react-dnd/lib/DragDropContext'>;
}
declare module 'react-dnd/lib/DragLayer.js' {
  declare module.exports: $Exports<'react-dnd/lib/DragLayer'>;
}
declare module 'react-dnd/lib/DragSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/DragSource'>;
}
declare module 'react-dnd/lib/DropTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/DropTarget'>;
}
declare module 'react-dnd/lib/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/index'>;
}
declare module 'react-dnd/lib/interfaces.js' {
  declare module.exports: $Exports<'react-dnd/lib/interfaces'>;
}
declare module 'react-dnd/lib/registerSource.js' {
  declare module.exports: $Exports<'react-dnd/lib/registerSource'>;
}
declare module 'react-dnd/lib/registerTarget.js' {
  declare module.exports: $Exports<'react-dnd/lib/registerTarget'>;
}
declare module 'react-dnd/lib/utils/checkDecoratorArguments.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/checkDecoratorArguments'>;
}
declare module 'react-dnd/lib/utils/cloneWithRef.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/cloneWithRef'>;
}
declare module 'react-dnd/lib/utils/disposables/CompositeDisposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/disposables/CompositeDisposable'>;
}
declare module 'react-dnd/lib/utils/disposables/Disposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/disposables/Disposable'>;
}
declare module 'react-dnd/lib/utils/disposables/index.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/disposables/index'>;
}
declare module 'react-dnd/lib/utils/disposables/SerialDisposable.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/disposables/SerialDisposable'>;
}
declare module 'react-dnd/lib/utils/isValidType.js' {
  declare module.exports: $Exports<'react-dnd/lib/utils/isValidType'>;
}
declare module 'react-dnd/lib/wrapConnectorHooks.js' {
  declare module.exports: $Exports<'react-dnd/lib/wrapConnectorHooks'>;
}
