// flow-typed signature: 510ae300b33bc120227a364df114978b
// flow-typed version: <<STUB>>/react-dnd-html5-backend_v^5.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dnd-html5-backend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dnd-html5-backend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.min' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/BrowserDetector' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/EnterLeaveCounter' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/getEmptyImage' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/HTML5Backend' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/index' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/interfaces' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/MonotonicInterpolant' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/NativeDragSources' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/NativeTypes' {
  declare module.exports: any;
}

declare module 'react-dnd-html5-backend/lib/OffsetUtils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/ReactDnDHTML5Backend'>;
}
declare module 'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.min.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/dist/ReactDnDHTML5Backend.min'>;
}
declare module 'react-dnd-html5-backend/lib/BrowserDetector.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/BrowserDetector'>;
}
declare module 'react-dnd-html5-backend/lib/EnterLeaveCounter.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/EnterLeaveCounter'>;
}
declare module 'react-dnd-html5-backend/lib/getEmptyImage.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/getEmptyImage'>;
}
declare module 'react-dnd-html5-backend/lib/HTML5Backend.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/HTML5Backend'>;
}
declare module 'react-dnd-html5-backend/lib/index.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/index'>;
}
declare module 'react-dnd-html5-backend/lib/interfaces.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/interfaces'>;
}
declare module 'react-dnd-html5-backend/lib/MonotonicInterpolant.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/MonotonicInterpolant'>;
}
declare module 'react-dnd-html5-backend/lib/NativeDragSources.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeDragSources'>;
}
declare module 'react-dnd-html5-backend/lib/NativeTypes.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/NativeTypes'>;
}
declare module 'react-dnd-html5-backend/lib/OffsetUtils.js' {
  declare module.exports: $Exports<'react-dnd-html5-backend/lib/OffsetUtils'>;
}
