// flow-typed signature: b061a1962c29961d3a22d52d6916101e
// flow-typed version: <<STUB>>/sqlite-parser_v^1.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sqlite-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sqlite-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sqlite-parser/dist/sqlite-parser' {
  declare module.exports: any;
}

declare module 'sqlite-parser/lib/index' {
  declare module.exports: any;
}

declare module 'sqlite-parser/lib/parser' {
  declare module.exports: any;
}

declare module 'sqlite-parser/lib/streaming-shim' {
  declare module.exports: any;
}

declare module 'sqlite-parser/lib/streaming' {
  declare module.exports: any;
}

declare module 'sqlite-parser/lib/tracer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sqlite-parser/dist/sqlite-parser.js' {
  declare module.exports: $Exports<'sqlite-parser/dist/sqlite-parser'>;
}
declare module 'sqlite-parser/lib/index.js' {
  declare module.exports: $Exports<'sqlite-parser/lib/index'>;
}
declare module 'sqlite-parser/lib/parser.js' {
  declare module.exports: $Exports<'sqlite-parser/lib/parser'>;
}
declare module 'sqlite-parser/lib/streaming-shim.js' {
  declare module.exports: $Exports<'sqlite-parser/lib/streaming-shim'>;
}
declare module 'sqlite-parser/lib/streaming.js' {
  declare module.exports: $Exports<'sqlite-parser/lib/streaming'>;
}
declare module 'sqlite-parser/lib/tracer.js' {
  declare module.exports: $Exports<'sqlite-parser/lib/tracer'>;
}
