// flow-typed signature: 9e928c3bd16652c79993135bde438ab1
// flow-typed version: <<STUB>>/standard_v^8.4.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard/bin/cmd' {
  declare module.exports: any;
}

declare module 'standard/options' {
  declare module.exports: any;
}

declare module 'standard/test/api' {
  declare module.exports: any;
}

declare module 'standard/test/clone' {
  declare module.exports: any;
}

declare module 'standard/test/cmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard/bin/cmd.js' {
  declare module.exports: $Exports<'standard/bin/cmd'>;
}
declare module 'standard/index' {
  declare module.exports: $Exports<'standard'>;
}
declare module 'standard/index.js' {
  declare module.exports: $Exports<'standard'>;
}
declare module 'standard/options.js' {
  declare module.exports: $Exports<'standard/options'>;
}
declare module 'standard/test/api.js' {
  declare module.exports: $Exports<'standard/test/api'>;
}
declare module 'standard/test/clone.js' {
  declare module.exports: $Exports<'standard/test/clone'>;
}
declare module 'standard/test/cmd.js' {
  declare module.exports: $Exports<'standard/test/cmd'>;
}
