// flow-typed signature: 40dfc81c3f65b64cbb9c30474b960d4f
// flow-typed version: <<STUB>>/tap-summary_v^4.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap-summary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap-summary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tap-summary/bin/cmd' {
  declare module.exports: any;
}

declare module 'tap-summary/lib/formatter' {
  declare module.exports: any;
}

declare module 'tap-summary/lib/reporter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tap-summary/bin/cmd.js' {
  declare module.exports: $Exports<'tap-summary/bin/cmd'>;
}
declare module 'tap-summary/index' {
  declare module.exports: $Exports<'tap-summary'>;
}
declare module 'tap-summary/index.js' {
  declare module.exports: $Exports<'tap-summary'>;
}
declare module 'tap-summary/lib/formatter.js' {
  declare module.exports: $Exports<'tap-summary/lib/formatter'>;
}
declare module 'tap-summary/lib/reporter.js' {
  declare module.exports: $Exports<'tap-summary/lib/reporter'>;
}
