// flow-typed signature: 967cbf0beca478e54cdf8393186f8e74
// flow-typed version: <<STUB>>/tap-spec_v^4.1.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap-spec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap-spec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tap-spec/bin/cmd' {
  declare module.exports: any;
}

declare module 'tap-spec/lib/utils/l-trim-list' {
  declare module.exports: any;
}

declare module 'tap-spec/test/e2e/index' {
  declare module.exports: any;
}

declare module 'tap-spec/test/unit/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tap-spec/bin/cmd.js' {
  declare module.exports: $Exports<'tap-spec/bin/cmd'>;
}
declare module 'tap-spec/index' {
  declare module.exports: $Exports<'tap-spec'>;
}
declare module 'tap-spec/index.js' {
  declare module.exports: $Exports<'tap-spec'>;
}
declare module 'tap-spec/lib/utils/l-trim-list.js' {
  declare module.exports: $Exports<'tap-spec/lib/utils/l-trim-list'>;
}
declare module 'tap-spec/test/e2e/index.js' {
  declare module.exports: $Exports<'tap-spec/test/e2e/index'>;
}
declare module 'tap-spec/test/unit/index.js' {
  declare module.exports: $Exports<'tap-spec/test/unit/index'>;
}
