// flow-typed signature: 3b9f98420b334a0b68d2fe70d77a121a
// flow-typed version: <<STUB>>/@blueprintjs/icons_v^3.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@blueprintjs/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@blueprintjs/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@blueprintjs/icons/dist/icons.bundle' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/generated/iconContents' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/generated/iconNames' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/generated/iconSvgPaths' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/iconName' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/cjs/index' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/generated/iconContents' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/generated/iconNames' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/generated/iconSvgPaths' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/iconName' {
  declare module.exports: any;
}

declare module '@blueprintjs/icons/lib/esm/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@blueprintjs/icons/dist/icons.bundle.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/dist/icons.bundle'>;
}
declare module '@blueprintjs/icons/lib/cjs/generated/iconContents.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/generated/iconContents'>;
}
declare module '@blueprintjs/icons/lib/cjs/generated/iconNames.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/generated/iconNames'>;
}
declare module '@blueprintjs/icons/lib/cjs/generated/iconSvgPaths.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/generated/iconSvgPaths'>;
}
declare module '@blueprintjs/icons/lib/cjs/iconName.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/iconName'>;
}
declare module '@blueprintjs/icons/lib/cjs/index.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/cjs/index'>;
}
declare module '@blueprintjs/icons/lib/esm/generated/iconContents.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/generated/iconContents'>;
}
declare module '@blueprintjs/icons/lib/esm/generated/iconNames.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/generated/iconNames'>;
}
declare module '@blueprintjs/icons/lib/esm/generated/iconSvgPaths.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/generated/iconSvgPaths'>;
}
declare module '@blueprintjs/icons/lib/esm/iconName.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/iconName'>;
}
declare module '@blueprintjs/icons/lib/esm/index.js' {
  declare module.exports: $Exports<'@blueprintjs/icons/lib/esm/index'>;
}
