// flow-typed signature: 19f6fc096540e51834fd5f80d52880bb
// flow-typed version: <<STUB>>/byline_v^5.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'byline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'byline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'byline/lib/byline' {
  declare module.exports: any;
}

// Filename aliases
declare module 'byline/lib/byline.js' {
  declare module.exports: $Exports<'byline/lib/byline'>;
}
