// flow-typed signature: 8d4b6a360ca7f998a6ede662f6fedbd2
// flow-typed version: <<STUB>>/command-line-args_v^5.0.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'command-line-args'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'command-line-args' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'command-line-args/lib/argv-parser' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/option-definition' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/option-definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/option-flag' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/option' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/output-grouped' {
  declare module.exports: any;
}

declare module 'command-line-args/lib/output' {
  declare module.exports: any;
}

declare module 'command-line-args/test/alias' {
  declare module.exports: any;
}

declare module 'command-line-args/test/ambiguous-input' {
  declare module.exports: any;
}

declare module 'command-line-args/test/bad-input' {
  declare module.exports: any;
}

declare module 'command-line-args/test/camel-case' {
  declare module.exports: any;
}

declare module 'command-line-args/test/default-option' {
  declare module.exports: any;
}

declare module 'command-line-args/test/default-value' {
  declare module.exports: any;
}

declare module 'command-line-args/test/detect-process-argv' {
  declare module.exports: any;
}

declare module 'command-line-args/test/exceptions-already-set' {
  declare module.exports: any;
}

declare module 'command-line-args/test/exceptions-invalid-definition' {
  declare module.exports: any;
}

declare module 'command-line-args/test/exceptions-unknowns' {
  declare module.exports: any;
}

declare module 'command-line-args/test/grouping' {
  declare module.exports: any;
}

declare module 'command-line-args/test/internals/argv-parser' {
  declare module.exports: any;
}

declare module 'command-line-args/test/internals/option-default' {
  declare module.exports: any;
}

declare module 'command-line-args/test/internals/option-definitions' {
  declare module.exports: any;
}

declare module 'command-line-args/test/internals/option-flag' {
  declare module.exports: any;
}

declare module 'command-line-args/test/internals/option' {
  declare module.exports: any;
}

declare module 'command-line-args/test/internals/output' {
  declare module.exports: any;
}

declare module 'command-line-args/test/multiple-lazy' {
  declare module.exports: any;
}

declare module 'command-line-args/test/multiple' {
  declare module.exports: any;
}

declare module 'command-line-args/test/name-alias-mix' {
  declare module.exports: any;
}

declare module 'command-line-args/test/name-unicode' {
  declare module.exports: any;
}

declare module 'command-line-args/test/notations' {
  declare module.exports: any;
}

declare module 'command-line-args/test/partial' {
  declare module.exports: any;
}

declare module 'command-line-args/test/stop-at-first-unknown' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-boolean' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-none' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-number' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-other' {
  declare module.exports: any;
}

declare module 'command-line-args/test/type-string' {
  declare module.exports: any;
}

// Filename aliases
declare module 'command-line-args/index' {
  declare module.exports: $Exports<'command-line-args'>;
}
declare module 'command-line-args/index.js' {
  declare module.exports: $Exports<'command-line-args'>;
}
declare module 'command-line-args/lib/argv-parser.js' {
  declare module.exports: $Exports<'command-line-args/lib/argv-parser'>;
}
declare module 'command-line-args/lib/option-definition.js' {
  declare module.exports: $Exports<'command-line-args/lib/option-definition'>;
}
declare module 'command-line-args/lib/option-definitions.js' {
  declare module.exports: $Exports<'command-line-args/lib/option-definitions'>;
}
declare module 'command-line-args/lib/option-flag.js' {
  declare module.exports: $Exports<'command-line-args/lib/option-flag'>;
}
declare module 'command-line-args/lib/option.js' {
  declare module.exports: $Exports<'command-line-args/lib/option'>;
}
declare module 'command-line-args/lib/output-grouped.js' {
  declare module.exports: $Exports<'command-line-args/lib/output-grouped'>;
}
declare module 'command-line-args/lib/output.js' {
  declare module.exports: $Exports<'command-line-args/lib/output'>;
}
declare module 'command-line-args/test/alias.js' {
  declare module.exports: $Exports<'command-line-args/test/alias'>;
}
declare module 'command-line-args/test/ambiguous-input.js' {
  declare module.exports: $Exports<'command-line-args/test/ambiguous-input'>;
}
declare module 'command-line-args/test/bad-input.js' {
  declare module.exports: $Exports<'command-line-args/test/bad-input'>;
}
declare module 'command-line-args/test/camel-case.js' {
  declare module.exports: $Exports<'command-line-args/test/camel-case'>;
}
declare module 'command-line-args/test/default-option.js' {
  declare module.exports: $Exports<'command-line-args/test/default-option'>;
}
declare module 'command-line-args/test/default-value.js' {
  declare module.exports: $Exports<'command-line-args/test/default-value'>;
}
declare module 'command-line-args/test/detect-process-argv.js' {
  declare module.exports: $Exports<'command-line-args/test/detect-process-argv'>;
}
declare module 'command-line-args/test/exceptions-already-set.js' {
  declare module.exports: $Exports<'command-line-args/test/exceptions-already-set'>;
}
declare module 'command-line-args/test/exceptions-invalid-definition.js' {
  declare module.exports: $Exports<'command-line-args/test/exceptions-invalid-definition'>;
}
declare module 'command-line-args/test/exceptions-unknowns.js' {
  declare module.exports: $Exports<'command-line-args/test/exceptions-unknowns'>;
}
declare module 'command-line-args/test/grouping.js' {
  declare module.exports: $Exports<'command-line-args/test/grouping'>;
}
declare module 'command-line-args/test/internals/argv-parser.js' {
  declare module.exports: $Exports<'command-line-args/test/internals/argv-parser'>;
}
declare module 'command-line-args/test/internals/option-default.js' {
  declare module.exports: $Exports<'command-line-args/test/internals/option-default'>;
}
declare module 'command-line-args/test/internals/option-definitions.js' {
  declare module.exports: $Exports<'command-line-args/test/internals/option-definitions'>;
}
declare module 'command-line-args/test/internals/option-flag.js' {
  declare module.exports: $Exports<'command-line-args/test/internals/option-flag'>;
}
declare module 'command-line-args/test/internals/option.js' {
  declare module.exports: $Exports<'command-line-args/test/internals/option'>;
}
declare module 'command-line-args/test/internals/output.js' {
  declare module.exports: $Exports<'command-line-args/test/internals/output'>;
}
declare module 'command-line-args/test/multiple-lazy.js' {
  declare module.exports: $Exports<'command-line-args/test/multiple-lazy'>;
}
declare module 'command-line-args/test/multiple.js' {
  declare module.exports: $Exports<'command-line-args/test/multiple'>;
}
declare module 'command-line-args/test/name-alias-mix.js' {
  declare module.exports: $Exports<'command-line-args/test/name-alias-mix'>;
}
declare module 'command-line-args/test/name-unicode.js' {
  declare module.exports: $Exports<'command-line-args/test/name-unicode'>;
}
declare module 'command-line-args/test/notations.js' {
  declare module.exports: $Exports<'command-line-args/test/notations'>;
}
declare module 'command-line-args/test/partial.js' {
  declare module.exports: $Exports<'command-line-args/test/partial'>;
}
declare module 'command-line-args/test/stop-at-first-unknown.js' {
  declare module.exports: $Exports<'command-line-args/test/stop-at-first-unknown'>;
}
declare module 'command-line-args/test/type-boolean.js' {
  declare module.exports: $Exports<'command-line-args/test/type-boolean'>;
}
declare module 'command-line-args/test/type-none.js' {
  declare module.exports: $Exports<'command-line-args/test/type-none'>;
}
declare module 'command-line-args/test/type-number.js' {
  declare module.exports: $Exports<'command-line-args/test/type-number'>;
}
declare module 'command-line-args/test/type-other.js' {
  declare module.exports: $Exports<'command-line-args/test/type-other'>;
}
declare module 'command-line-args/test/type-string.js' {
  declare module.exports: $Exports<'command-line-args/test/type-string'>;
}
