// flow-typed signature: 80f471774bd5355501597884438b224a
// flow-typed version: <<STUB>>/csv-sniffer_v^0.1.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csv-sniffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csv-sniffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'csv-sniffer/index' {
  declare module.exports: $Exports<'csv-sniffer'>;
}
declare module 'csv-sniffer/index.js' {
  declare module.exports: $Exports<'csv-sniffer'>;
}
