// flow-typed signature: a34139d82b959a5f3737ab6737fa19d1
// flow-typed version: <<STUB>>/d3-fetch_v1.1.2/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'd3-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'd3-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'd3-fetch/dist/d3-fetch' {
  declare module.exports: any;
}

declare module 'd3-fetch/dist/d3-fetch.min' {
  declare module.exports: any;
}

declare module 'd3-fetch/rollup.config' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/blob' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/buffer' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/dsv' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/image' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/index' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/json' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/text' {
  declare module.exports: any;
}

declare module 'd3-fetch/src/xml' {
  declare module.exports: any;
}

// Filename aliases
declare module 'd3-fetch/dist/d3-fetch.js' {
  declare module.exports: $Exports<'d3-fetch/dist/d3-fetch'>;
}
declare module 'd3-fetch/dist/d3-fetch.min.js' {
  declare module.exports: $Exports<'d3-fetch/dist/d3-fetch.min'>;
}
declare module 'd3-fetch/rollup.config.js' {
  declare module.exports: $Exports<'d3-fetch/rollup.config'>;
}
declare module 'd3-fetch/src/blob.js' {
  declare module.exports: $Exports<'d3-fetch/src/blob'>;
}
declare module 'd3-fetch/src/buffer.js' {
  declare module.exports: $Exports<'d3-fetch/src/buffer'>;
}
declare module 'd3-fetch/src/dsv.js' {
  declare module.exports: $Exports<'d3-fetch/src/dsv'>;
}
declare module 'd3-fetch/src/image.js' {
  declare module.exports: $Exports<'d3-fetch/src/image'>;
}
declare module 'd3-fetch/src/index.js' {
  declare module.exports: $Exports<'d3-fetch/src/index'>;
}
declare module 'd3-fetch/src/json.js' {
  declare module.exports: $Exports<'d3-fetch/src/json'>;
}
declare module 'd3-fetch/src/text.js' {
  declare module.exports: $Exports<'d3-fetch/src/text'>;
}
declare module 'd3-fetch/src/xml.js' {
  declare module.exports: $Exports<'d3-fetch/src/xml'>;
}
