// flow-typed signature: f814b403c4c75c7e8d8914aeec02412d
// flow-typed version: <<STUB>>/difflet_v^1.0.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'difflet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'difflet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'difflet/example/cmp_array' {
  declare module.exports: any;
}

declare module 'difflet/example/cmp_object' {
  declare module.exports: any;
}

declare module 'difflet/example/colors' {
  declare module.exports: any;
}

declare module 'difflet/example/comma_first' {
  declare module.exports: any;
}

declare module 'difflet/example/deep_array' {
  declare module.exports: any;
}

declare module 'difflet/example/diff' {
  declare module.exports: any;
}

declare module 'difflet/example/html' {
  declare module.exports: any;
}

declare module 'difflet/example/string' {
  declare module.exports: any;
}

declare module 'difflet/test/diffing-NaN' {
  declare module.exports: any;
}

declare module 'difflet/test/html' {
  declare module.exports: any;
}

declare module 'difflet/test/object_tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'difflet/example/cmp_array.js' {
  declare module.exports: $Exports<'difflet/example/cmp_array'>;
}
declare module 'difflet/example/cmp_object.js' {
  declare module.exports: $Exports<'difflet/example/cmp_object'>;
}
declare module 'difflet/example/colors.js' {
  declare module.exports: $Exports<'difflet/example/colors'>;
}
declare module 'difflet/example/comma_first.js' {
  declare module.exports: $Exports<'difflet/example/comma_first'>;
}
declare module 'difflet/example/deep_array.js' {
  declare module.exports: $Exports<'difflet/example/deep_array'>;
}
declare module 'difflet/example/diff.js' {
  declare module.exports: $Exports<'difflet/example/diff'>;
}
declare module 'difflet/example/html.js' {
  declare module.exports: $Exports<'difflet/example/html'>;
}
declare module 'difflet/example/string.js' {
  declare module.exports: $Exports<'difflet/example/string'>;
}
declare module 'difflet/index' {
  declare module.exports: $Exports<'difflet'>;
}
declare module 'difflet/index.js' {
  declare module.exports: $Exports<'difflet'>;
}
declare module 'difflet/test/diffing-NaN.js' {
  declare module.exports: $Exports<'difflet/test/diffing-NaN'>;
}
declare module 'difflet/test/html.js' {
  declare module.exports: $Exports<'difflet/test/html'>;
}
declare module 'difflet/test/object_tests.js' {
  declare module.exports: $Exports<'difflet/test/object_tests'>;
}
