// flow-typed signature: f30a85aac9e50c06c77d2eb5b2aeef66
// flow-typed version: <<STUB>>/gauge_v^2.7.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gauge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gauge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gauge/base-theme' {
  declare module.exports: any;
}

declare module 'gauge/error' {
  declare module.exports: any;
}

declare module 'gauge/has-color' {
  declare module.exports: any;
}

declare module 'gauge/plumbing' {
  declare module.exports: any;
}

declare module 'gauge/process' {
  declare module.exports: any;
}

declare module 'gauge/progress-bar' {
  declare module.exports: any;
}

declare module 'gauge/render-template' {
  declare module.exports: any;
}

declare module 'gauge/set-immediate' {
  declare module.exports: any;
}

declare module 'gauge/set-interval' {
  declare module.exports: any;
}

declare module 'gauge/spin' {
  declare module.exports: any;
}

declare module 'gauge/template-item' {
  declare module.exports: any;
}

declare module 'gauge/theme-set' {
  declare module.exports: any;
}

declare module 'gauge/themes' {
  declare module.exports: any;
}

declare module 'gauge/wide-truncate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gauge/base-theme.js' {
  declare module.exports: $Exports<'gauge/base-theme'>;
}
declare module 'gauge/error.js' {
  declare module.exports: $Exports<'gauge/error'>;
}
declare module 'gauge/has-color.js' {
  declare module.exports: $Exports<'gauge/has-color'>;
}
declare module 'gauge/index' {
  declare module.exports: $Exports<'gauge'>;
}
declare module 'gauge/index.js' {
  declare module.exports: $Exports<'gauge'>;
}
declare module 'gauge/plumbing.js' {
  declare module.exports: $Exports<'gauge/plumbing'>;
}
declare module 'gauge/process.js' {
  declare module.exports: $Exports<'gauge/process'>;
}
declare module 'gauge/progress-bar.js' {
  declare module.exports: $Exports<'gauge/progress-bar'>;
}
declare module 'gauge/render-template.js' {
  declare module.exports: $Exports<'gauge/render-template'>;
}
declare module 'gauge/set-immediate.js' {
  declare module.exports: $Exports<'gauge/set-immediate'>;
}
declare module 'gauge/set-interval.js' {
  declare module.exports: $Exports<'gauge/set-interval'>;
}
declare module 'gauge/spin.js' {
  declare module.exports: $Exports<'gauge/spin'>;
}
declare module 'gauge/template-item.js' {
  declare module.exports: $Exports<'gauge/template-item'>;
}
declare module 'gauge/theme-set.js' {
  declare module.exports: $Exports<'gauge/theme-set'>;
}
declare module 'gauge/themes.js' {
  declare module.exports: $Exports<'gauge/themes'>;
}
declare module 'gauge/wide-truncate.js' {
  declare module.exports: $Exports<'gauge/wide-truncate'>;
}
