// flow-typed signature: e87f3858a23e4bcadfcbc7958c8e21a4
// flow-typed version: <<STUB>>/image-webpack-loader_v^4.4.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-webpack-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-webpack-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'image-webpack-loader/test/app' {
  declare module.exports: any;
}

declare module 'image-webpack-loader/test/webpack1.config' {
  declare module.exports: any;
}

declare module 'image-webpack-loader/test/webpack2.config' {
  declare module.exports: any;
}

declare module 'image-webpack-loader/test/webpack4.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'image-webpack-loader/index' {
  declare module.exports: $Exports<'image-webpack-loader'>;
}
declare module 'image-webpack-loader/index.js' {
  declare module.exports: $Exports<'image-webpack-loader'>;
}
declare module 'image-webpack-loader/test/app.js' {
  declare module.exports: $Exports<'image-webpack-loader/test/app'>;
}
declare module 'image-webpack-loader/test/webpack1.config.js' {
  declare module.exports: $Exports<'image-webpack-loader/test/webpack1.config'>;
}
declare module 'image-webpack-loader/test/webpack2.config.js' {
  declare module.exports: $Exports<'image-webpack-loader/test/webpack2.config'>;
}
declare module 'image-webpack-loader/test/webpack4.config.js' {
  declare module.exports: $Exports<'image-webpack-loader/test/webpack4.config'>;
}
