// flow-typed signature: 795b8c8d9af9dd4f5c49884cacfd4b6e
// flow-typed version: <<STUB>>/jsesc_v^2.5.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jsesc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jsesc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jsesc/jsesc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jsesc/jsesc.js' {
  declare module.exports: $Exports<'jsesc/jsesc'>;
}
