// flow-typed signature: 97c8ecbd489d92fd248bb38c1d0b9cba
// flow-typed version: <<STUB>>/leaked-handles_v^5.2.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'leaked-handles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'leaked-handles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'leaked-handles/print-handle' {
  declare module.exports: any;
}

declare module 'leaked-handles/print-handles' {
  declare module.exports: any;
}

declare module 'leaked-handles/stacks' {
  declare module.exports: any;
}

declare module 'leaked-handles/test/index' {
  declare module.exports: any;
}

declare module 'leaked-handles/test/leak-child-process' {
  declare module.exports: any;
}

declare module 'leaked-handles/test/leak-http-server' {
  declare module.exports: any;
}

declare module 'leaked-handles/test/leak-http' {
  declare module.exports: any;
}

declare module 'leaked-handles/test/leak-tcp' {
  declare module.exports: any;
}

declare module 'leaked-handles/test/leak-timer' {
  declare module.exports: any;
}

declare module 'leaked-handles/test/lib/fake-logger' {
  declare module.exports: any;
}

// Filename aliases
declare module 'leaked-handles/index' {
  declare module.exports: $Exports<'leaked-handles'>;
}
declare module 'leaked-handles/index.js' {
  declare module.exports: $Exports<'leaked-handles'>;
}
declare module 'leaked-handles/print-handle.js' {
  declare module.exports: $Exports<'leaked-handles/print-handle'>;
}
declare module 'leaked-handles/print-handles.js' {
  declare module.exports: $Exports<'leaked-handles/print-handles'>;
}
declare module 'leaked-handles/stacks.js' {
  declare module.exports: $Exports<'leaked-handles/stacks'>;
}
declare module 'leaked-handles/test/index.js' {
  declare module.exports: $Exports<'leaked-handles/test/index'>;
}
declare module 'leaked-handles/test/leak-child-process.js' {
  declare module.exports: $Exports<'leaked-handles/test/leak-child-process'>;
}
declare module 'leaked-handles/test/leak-http-server.js' {
  declare module.exports: $Exports<'leaked-handles/test/leak-http-server'>;
}
declare module 'leaked-handles/test/leak-http.js' {
  declare module.exports: $Exports<'leaked-handles/test/leak-http'>;
}
declare module 'leaked-handles/test/leak-tcp.js' {
  declare module.exports: $Exports<'leaked-handles/test/leak-tcp'>;
}
declare module 'leaked-handles/test/leak-timer.js' {
  declare module.exports: $Exports<'leaked-handles/test/leak-timer'>;
}
declare module 'leaked-handles/test/lib/fake-logger.js' {
  declare module.exports: $Exports<'leaked-handles/test/lib/fake-logger'>;
}
