// flow-typed signature: 89248ff08ff0bed0dc369c0b849d6059
// flow-typed version: <<STUB>>/node-gyp_v^3.8.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-gyp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-gyp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-gyp/bin/node-gyp' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/build' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/clean' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/configure' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/find-node-directory' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/find-vs2017' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/install' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/list' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/node-gyp' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/process-release' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/rebuild' {
  declare module.exports: any;
}

declare module 'node-gyp/lib/remove' {
  declare module.exports: any;
}

declare module 'node-gyp/test/process-exec-sync' {
  declare module.exports: any;
}

declare module 'node-gyp/test/simple-proxy' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-addon' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-configure-python' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-download' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-find-accessible-sync' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-find-node-directory' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-find-python' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-install' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-options' {
  declare module.exports: any;
}

declare module 'node-gyp/test/test-process-release' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-gyp/bin/node-gyp.js' {
  declare module.exports: $Exports<'node-gyp/bin/node-gyp'>;
}
declare module 'node-gyp/lib/build.js' {
  declare module.exports: $Exports<'node-gyp/lib/build'>;
}
declare module 'node-gyp/lib/clean.js' {
  declare module.exports: $Exports<'node-gyp/lib/clean'>;
}
declare module 'node-gyp/lib/configure.js' {
  declare module.exports: $Exports<'node-gyp/lib/configure'>;
}
declare module 'node-gyp/lib/find-node-directory.js' {
  declare module.exports: $Exports<'node-gyp/lib/find-node-directory'>;
}
declare module 'node-gyp/lib/find-vs2017.js' {
  declare module.exports: $Exports<'node-gyp/lib/find-vs2017'>;
}
declare module 'node-gyp/lib/install.js' {
  declare module.exports: $Exports<'node-gyp/lib/install'>;
}
declare module 'node-gyp/lib/list.js' {
  declare module.exports: $Exports<'node-gyp/lib/list'>;
}
declare module 'node-gyp/lib/node-gyp.js' {
  declare module.exports: $Exports<'node-gyp/lib/node-gyp'>;
}
declare module 'node-gyp/lib/process-release.js' {
  declare module.exports: $Exports<'node-gyp/lib/process-release'>;
}
declare module 'node-gyp/lib/rebuild.js' {
  declare module.exports: $Exports<'node-gyp/lib/rebuild'>;
}
declare module 'node-gyp/lib/remove.js' {
  declare module.exports: $Exports<'node-gyp/lib/remove'>;
}
declare module 'node-gyp/test/process-exec-sync.js' {
  declare module.exports: $Exports<'node-gyp/test/process-exec-sync'>;
}
declare module 'node-gyp/test/simple-proxy.js' {
  declare module.exports: $Exports<'node-gyp/test/simple-proxy'>;
}
declare module 'node-gyp/test/test-addon.js' {
  declare module.exports: $Exports<'node-gyp/test/test-addon'>;
}
declare module 'node-gyp/test/test-configure-python.js' {
  declare module.exports: $Exports<'node-gyp/test/test-configure-python'>;
}
declare module 'node-gyp/test/test-download.js' {
  declare module.exports: $Exports<'node-gyp/test/test-download'>;
}
declare module 'node-gyp/test/test-find-accessible-sync.js' {
  declare module.exports: $Exports<'node-gyp/test/test-find-accessible-sync'>;
}
declare module 'node-gyp/test/test-find-node-directory.js' {
  declare module.exports: $Exports<'node-gyp/test/test-find-node-directory'>;
}
declare module 'node-gyp/test/test-find-python.js' {
  declare module.exports: $Exports<'node-gyp/test/test-find-python'>;
}
declare module 'node-gyp/test/test-install.js' {
  declare module.exports: $Exports<'node-gyp/test/test-install'>;
}
declare module 'node-gyp/test/test-options.js' {
  declare module.exports: $Exports<'node-gyp/test/test-options'>;
}
declare module 'node-gyp/test/test-process-release.js' {
  declare module.exports: $Exports<'node-gyp/test/test-process-release'>;
}
