// flow-typed signature: f4ca0ec8c4645c7895b95cba3fb9f54d
// flow-typed version: <<STUB>>/react-window-size-listener_v^1.2.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-window-size-listener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-window-size-listener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-window-size-listener/lib/index' {
  declare module.exports: any;
}

declare module 'react-window-size-listener/src/index' {
  declare module.exports: any;
}

declare module 'react-window-size-listener/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-window-size-listener/lib/index.js' {
  declare module.exports: $Exports<'react-window-size-listener/lib/index'>;
}
declare module 'react-window-size-listener/src/index.js' {
  declare module.exports: $Exports<'react-window-size-listener/src/index'>;
}
declare module 'react-window-size-listener/webpack.config.js' {
  declare module.exports: $Exports<'react-window-size-listener/webpack.config'>;
}
