// flow-typed signature: a340bef84923e9b60b6198865681d365
// flow-typed version: <<STUB>>/slickgrid-es6_v^2.1.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slickgrid-es6'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slickgrid-es6' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slickgrid-es6/dist/slick.es6.min' {
  declare module.exports: any;
}

declare module 'slickgrid-es6/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slickgrid-es6/dist/slick.es6.min.js' {
  declare module.exports: $Exports<'slickgrid-es6/dist/slick.es6.min'>;
}
declare module 'slickgrid-es6/webpack.config.js' {
  declare module.exports: $Exports<'slickgrid-es6/webpack.config'>;
}
