// flow-typed signature: 8eb68c811b241db8aae2be314bf66001
// flow-typed version: <<STUB>>/source-map-loader_v^0.2.4/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-map-loader/test/fixtures/absolute-sourceRoot-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/charset-inline-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/external-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/external-source-map2' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/inline-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/invalid-inline-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/invalid-inline-source-map2' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/invalid-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/missing-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/missing-source-map2' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/multi-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/normal-file' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/fixtures/relative-sourceRoot-source-map' {
  declare module.exports: any;
}

declare module 'source-map-loader/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-map-loader/index' {
  declare module.exports: $Exports<'source-map-loader'>;
}
declare module 'source-map-loader/index.js' {
  declare module.exports: $Exports<'source-map-loader'>;
}
declare module 'source-map-loader/test/fixtures/absolute-sourceRoot-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/absolute-sourceRoot-source-map'>;
}
declare module 'source-map-loader/test/fixtures/charset-inline-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/charset-inline-source-map'>;
}
declare module 'source-map-loader/test/fixtures/external-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/external-source-map'>;
}
declare module 'source-map-loader/test/fixtures/external-source-map2.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/external-source-map2'>;
}
declare module 'source-map-loader/test/fixtures/inline-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/inline-source-map'>;
}
declare module 'source-map-loader/test/fixtures/invalid-inline-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/invalid-inline-source-map'>;
}
declare module 'source-map-loader/test/fixtures/invalid-inline-source-map2.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/invalid-inline-source-map2'>;
}
declare module 'source-map-loader/test/fixtures/invalid-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/invalid-source-map'>;
}
declare module 'source-map-loader/test/fixtures/missing-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/missing-source-map'>;
}
declare module 'source-map-loader/test/fixtures/missing-source-map2.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/missing-source-map2'>;
}
declare module 'source-map-loader/test/fixtures/multi-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/multi-source-map'>;
}
declare module 'source-map-loader/test/fixtures/normal-file.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/normal-file'>;
}
declare module 'source-map-loader/test/fixtures/relative-sourceRoot-source-map.js' {
  declare module.exports: $Exports<'source-map-loader/test/fixtures/relative-sourceRoot-source-map'>;
}
declare module 'source-map-loader/test/index.test.js' {
  declare module.exports: $Exports<'source-map-loader/test/index.test'>;
}
