// flow-typed signature: dc7e1e093d7abede5ff7ddb98b634d86
// flow-typed version: <<STUB>>/tap-difflet_v^0.7.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tap-difflet'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tap-difflet' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tap-difflet/index' {
  declare module.exports: $Exports<'tap-difflet'>;
}
declare module 'tap-difflet/index.js' {
  declare module.exports: $Exports<'tap-difflet'>;
}
