// flow-typed signature: 5783bf9cc7e5f0a0369f5c1af76d3406
// flow-typed version: <<STUB>>/@babel/preset-stage-3_v^7.0.0/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-stage-3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-stage-3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-stage-3/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-stage-3/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-stage-3/lib/index'>;
}
